title = "Cybernauterne"
baseURL = "https://cybernauterne.dk/"
languageCode = "da-dk"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Workshops"
    url = "/workshops"
  # [[menu.header]]
  #   weight = 3
  #   name = "Blog"
  #   url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Profiler"
    url = "/profiler"
  [[menu.header]]
    weight = 5
    name = "Materialer"
    url = "/materialer"
  [[menu.header]]
    weight = 6
    name = "Kontakt"
    url = "/kontakt"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Cybernauterne er et netværk af eksperter"
    subtitle = "Vi tilbyder træninger, rådgivning, workshops og foredrag om cybersikkerhed og digital dannelse."

  [params.wrapper]
    enable = true
    title = "Om Cybernauterne"
   # italic = "Cybernauterne er et netværk af eksperter der tilbyder træninger, rådgivning, workshops og foredrag om cybersikkerhed og digital dannelse."
    paragraph = "Vi er specialiseret i at formidle til folk, der ikke er IT-nørder eller har stor teknisk forståelse, og vi bruger inddragelse, kreative metoder og åbne workshop-formater til at indføre folk i alt fra falske nyheder, privatliv på nettet, algoritmernes magt, omgangsform på de sociale medier og sikkerhedstips til at beskytte sig mod hackere og IT-kriminelle."


  [params.materialer]
    enable = true
    title = "Materialer"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = false
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"


  [params.call]
    enable = true
    title = "- Cybernauterne er eksperter og det er rart at opleve."
    paragraph = "- Anonym kursusdeltager"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = ""
